### ISSUE TITLE
ch4 fedback from #forum-rhel-for-edge

### ISSUE THREAD

**Issue by flozanorht** [RedHatQuickCourses/rhde-build#9]
https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729706061627349?thread_ts=1727882423.812229&cid=C04MTCTF6SF

micah
  Today at 2:54 PM

> In case you download further system updates, the one not currently active is discarded to give room to the new updates, so there’s at most two system images in edge devices and you don’t need to prune old updates nor risk exhausting disk space on the devices.

While the update mechanism does prune older data that is no longer needed, you can end up in a situation where there is 3 deployments.  Consider the case where I have a system booted into commiit B and commit A is my rollback commit.  When I upgrade to commit C, that commit is staged until the system is rebooted. At that time, if I were to inspect the system with rpm-ostree status I would see commit C as pending, commit B as booted, and commit A as the rollback.

NEW

micah
  [Today at 2:58 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729706298399719?

> thread_ts=1727882423.812229&cid=C04MTCTF6SF)
> An edge commit image built with a reference to a parent commit is still a complete system image. It contains all files on the image, and the edge commit image contains an OSTree repo with a single commit, without previous history.

nit: the previous history is not contained in the edge commit, but there is a reference to the parent commit.

micah
  [Today at 3:02 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729706526605409?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

> It is perfectly fine if an edge commit image contains a remote which points to an OSTree repository which is not the one serving it. During testing you usually deploy a test VM (or phisical device) as that’s being provisioned for the first time. But, if you testing requires the RPM-OSTree update process, to perform tasks such as data schema migration, you can override the remote reference on the test machine before applying an update.

This part feels awkward. I'd suggest omitting all of it.

micah
  [Today at 3:05 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729706710327809?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

> Unlike Git, which is designed to keep a complete history of changes to source code, OSTree is not designed to keep a complete history of binary system images. That means you must be careful to preserve the chain of each commit to its parent.

I don't think this is a valid statement. The ostree architecture does allow for preservation of the history of a branch/ref, but it is up to the tools that leverage ostree to correctly use that feature. Just because the osbuild process requires some additional options to preserve the history, doesn't mean that ostree can't keep a commit history.

micah
  [Today at 3:07 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729706838631239?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

> You do not need to prune the local OSTree repository of an edge device because RPM-OStree does that automatically, always keeping at most two system images in the device.

See my previous comment about how many images can be kept on a device.  (Going further, you can use ostree admin pin to preserve multiple commits on a device, but that is likely impractical for Edge devices)

micah
  [Today at 3:11 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729707112461719?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

> Pruning OSTree Repositories

This section talks a lot about why pruning might be necessary in different scenarios, but it falls short of covering how to perform pruning of older commits in the repo.  i.e. ostree prune --delete-commi=<hash> or ostree prune --keep-younger-than=<DATE>

micah
  [Today at 3:14 PM](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729707261189179?thread_ts=1727882423.812229&cid=C04MTCTF6SF)
OSTree static delta helps 

> edge devices with bad network connectivity downloading system updates in a more efficient way.

I'd suggest rephrasing this to be more generic, like:  "OSTree static deltas can be used to provide system updates to edge devices where limiting the amount of network transactions is a concern."
i.e. it's not just for situations where there is "bad network connectivity"

micah
  [1 hour ago](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729707759078729?thread_ts=1727882423.812229&cid=C04MTCTF6SF)
[@Fernando Lozano](https://redhat-internal.slack.com/team/UDRP959CL)
 this is excellent content!  really comprehensive and does a great job explaining all the concepts.  customers should be excited to get their hands on this lab!

Fernando Lozano
  8 minutes ago
[@micah](https://redhat-internal.slack.com/team/U9C4P0LA2)
 regarding:

>  nit: the previous history is not contained in the edge commit, but there is a reference to the parent commit.

I think we're saying the same thing (so I must say it in a clearer way): an edge commit for an update contains only the files changed for the last commit. It doesn't contains the files that remain unchanged from its parent commit, because it assumes the consumer of the image has access to that parent commit. Is that right?

Fernando Lozano
  7 minutes ago
And now I realize I said "complete system image", implying the files form the parent would be in the edge commit image. They won't, right? (edited) 

Fernando Lozano
  [5 minutes ago](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729711028471109?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

>  This part feels awkward. I'd suggest omitting all of it.

Let's see if I can find a better wording.  I want to make sense of promoting images between repos, and that not all repos would have the complete history. For people used to git, you must have complete history in all forks.

micah
  [4 minutes ago](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729711055079739?thread_ts=1727882423.812229&cid=C04MTCTF6SF)

> an edge commit for an update contains only the files changed for the last commit. It doesn't contains the files that remain unchanged from its parent commit, because it assumes the consumer of the image has access to that parent commit. Is that right?

the update commit is still a complete commit.  the client (i.e. rpm-ostree) can compute which files have changed between the two commits and will only request the files that have changed.
in a different scenario, if a client was rebasing to the update commit, the update commit would have to be complete otherwise it wouldn't be possible to use.

Fernando Lozano
  4 minutes ago
By "complete commit" you mean it contains all files, even files that didn't change?

micah
  [3 minutes ago](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729711127069549?thread_ts=1727882423.812229&cid=C04MTCTF6SF)
pretty much. i think the implementation is that there are "references" to the files in the metadata and the client knows how to fetch the actual content (i.e. files)

micah
  2 minutes ago
to illustrate this a bit more, consider this:
i have a ref rhel/9/x86_64/edge with commit A and commit B (parent is A)
i have another ref rhel/9/x86_64/server with commit C and commit D (parent is C)
A device that is currently using rhel/9/x86_64/edge can do rpm-ostree rebase rhel/9/x86_64/server and it will be able to fetch all the files contained in commit D (which include files referenced in commit C)
hence, any commit in the ostree repo is technically a "complete commit"

Fernando Lozano
  1 minute ago
I think the source of my confusion regarding "a complete commit" and "a complete system image" is what files are actually in an edge commit image, when you download it from image builder. The tarball will contain only files changed on the last commit (which is the single on in the tarball) or will contain also the files from the parent and previous in history?
I was thinking it would be all files, no matter if they changed or not in the last commit, but edge devices supposedly have access to the parent and previous commit on their remote OSTree repos, so they don't need those files in the edge commit image. And, if I build an installer image, I'm not using an edge commit image, I'm using an OSTree repos which contains the commit and also previous history.
And I think I am overthinking the issue. In the end, you must build an image with a parent, and add it to a repository which has that parent, and that's all that matters.

micah
:spiral_calendar_pad:  [Just now](https://redhat-internal.slack.com/archives/C04MTCTF6SF/p1729711833442519?thread_ts=1727882423.812229&cid=C04MTCTF6SF)
the edge-commit tarball contains the "complete commit" or the "complete system image".  the reference to the parent commit is just in the metadata.

**Comment by miabbott** [comment]
@flozanorht feel free to engage me here on github for additional feedback.

i might go through the files here and submit my own PRs/issues.  :smile:

**Comment by flozanorht** [comment]
@miabbott new issues here or PRs are welcome! Please contact me if you need access to this repository.
